name: release @akashic package
description: publish and create release note
inputs:
  github_token:
    required: true
  npm_token:
    required: true
  only_pull_request:
    required: false
    type: boolean
    default: false
runs:
  using: node20
  main: dist/index.js
