name: release @akashic package
description: publish and create release note
inputs:
  git_repository:
    description: Git repository
    required: true
  target_branch:
    description: Target Branch
    required: true
    default: master
  target_npm_tag:
    description: Target Npm tag
    required: true
    default: latest
  target_dir_path:
    required: true
  github_token:
    required: true
  npm_token:
    required: true
runs:
  using: node12
  main: dist/index.js
